### ISSUE TITLE
Impact of road width

### ISSUE THREAD

**Issue by sidgitind** [Ujwal2910/Smart-Traffic-Signals-in-India-using-Deep-Reinforcement-Learning-and-Advanced-Computer-Vision#1]
Your work looks very interesting. In India, one of the key reason for traffic jam is non-uniform road width. A 4 lane highway could have a right turn and the width of the right turn road could support only 1 lane. Is it possible in check How does this impact the traffic and how can it be detected as the bottleneck?

**Comment by Ujwal2910** [comment]
In the Sumo simulation you can create roads for variable widths, wider roads converging to narrower ones. 
Then prepare similar baseline cases for multiple scenarios and then later prepare a comprehensive per Junction Average wait time for each vehicle or even density per lane per junction. These comparisons can be used to narrow down the problem as well the solution itself then.
